name: CI (lint & test)

on:
  pull_request:
    branches: ["develop"]
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/ci.yml"
      - ".eslintrc.json"
      - "tsconfig.json"
      - "tsconfig.*.json"
      - "angular.json"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: "npm"

      - name: Install dependencies
        run: npm ci --registry=https://registry.npmjs.org

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --watch=false --browsers=ChromeHeadless
